export const SHADER_PATHS = [
    './shaders/main.js',
    './shaders/main2.js',
    './shaders/main3.js',
    './shaders/main4.js',
];

export const KNOWLEDGE_ENTRIES = {
    'design-thinking': {
        mdPath: 'content/knowledge/design-thinking-{lang}.md',
        pdfUrl: 'https://uminomae.github.io/pjdhiro/assets/project-design/knowledge/ja/pdf/design-thinking.pdf',
        titleKey: 'knowledge.designThinking.title',
    },
    'trust': {
        mdPath: 'content/knowledge/trust-{lang}.md',
        pdfUrl: 'https://uminomae.github.io/pjdhiro/assets/project-design/knowledge/ja/pdf/trust.pdf',
        titleKey: 'knowledge.trust.title',
    },
    'value': {
        mdPath: 'content/knowledge/value-{lang}.md',
        pdfUrl: 'https://uminomae.github.io/pjdhiro/assets/project-design/knowledge/ja/pdf/value.pdf',
        titleKey: 'knowledge.value.title',
    },
};

export const MENU_ITEMS = [
    { type: 'label', labelKey: 'menu.sites' },
    { type: 'link', href: '/project-design/', labelKey: 'menu.home', className: 'menu-current' },
    { type: 'link', href: '/kesson-space/', labelKey: 'menu.kesson' },
    { type: 'link', href: '/creation-space/', labelKey: 'menu.creation' },
    { type: 'link', href: '/awareness-space/', labelKey: 'menu.awareness' },
    { type: 'link', href: '/pjdhiro/', labelKey: 'menu.blog' },
    { type: 'separator' },
    { type: 'label', labelKey: 'menu.researchNotes' },
    { type: 'knowledge-link', key: 'design-thinking', href: '?knowledge=design-thinking' },
    { type: 'knowledge-link', key: 'trust', href: '?knowledge=trust' },
    { type: 'knowledge-link', key: 'value', href: '?knowledge=value' },
];

export const TRANSLATIONS = {
    ja: {
        'menu.toggle': 'Menu',
        'menu.sites': 'Sites',
        'menu.home': 'HOME',
        'menu.kesson': '欠損駆動思考',
        'menu.creation': '創造とは',
        'menu.awareness': '意識とは',
        'menu.blog': 'BLOG',
        'menu.researchNotes': '調査ノート',
        'controls.topBarAria': 'サイト操作',
        'controls.languageAria': '言語切替',
        'hero.notice': 'Love駆動開発と呼びたい現象を、これまで何度も経験してきました。<br>ここでいうプロジェクトは「やること（Doing）」だけでなく「起きていること（Being）」まで含む出来事です。',
        'hero.aboutAria': 'このサイトについて',
        'section.overview.label': 'Overview',
        'section.overview.title': '概要',
        'overview.p1': 'プロジェクトデザインとは、プロジェクトの構想・設計・実行だけでなく、実行・管理の方法そのものを対象化し、構想・設計する営みです。',
        'overview.p2': 'まず、その基底として射程と領域を固定し、以降の議論を「やること（Doing）」と「起きてること（Being）」に分けて整理します。',
        'overview.p3': 'プロジェクト実務は、環境適応（物質的条件）とコミュニケーション（非物質的条件）に大別できます。本サイトでは環境適応を前提知（PMBOK等）とし、コミュニケーションを情報処理／感情処理に分解して、とくに感情処理を中心に扱います。',
        'overview.definition.title': '定義',
        'overview.definition.item1': 'プロジェクトの構想・設計・実行',
        'overview.definition.item2': '実行・管理方法の構想・設計',
        'overview.scope.title': '射程',
        'overview.scope.body': '営利・非営利の事業を主たる適用対象とする。研究、人生など、主体が目的を持って行為する営み一般に適用できる。',
        'overview.domain.title': '領域',
        'overview.domain.body': 'コミュニケーション（情報処理＋感情処理）と環境適応（経営学など）',
        'section.doing.label': 'Doing',
        'section.doing.title': 'やること',
        'doing.principles.title': '行動原理',
        'doing.principles.item1': '多様な価値観を受容れる',
        'doing.principles.item2': 'バランスを達成する',
        'doing.principles.item3': '状況に常に適応する',
        'doing.environment.title': '環境適応',
        'doing.environment.body': '「PMBOK第7版」等に基づく物質的条件の整理。本サイトでは前提知とし、非物質的条件へ焦点を当てます。',
        'doing.communication.title': 'コミュニケーション',
        'doing.communication.body': '情報処理と感情処理。心の反応を通じて感じ取る感情の側面を中心に扱います。',
        'pill.kesson': '欠損駆動思考',
        'pill.beauty': '美駆動思考',
        'pill.emotionalProcessing': '感情処理（総論）',
        'pill.meditation': '瞑想',
        'section.being.label': 'Being',
        'section.being.title': '起きていること',
        'section.being.body': '場（Field）が現れ、差異＝波（Wave）が立ち上がり、縁＝境界（Relation）が結ばれ、衝突が渦（Spinor）として回り、成果が束（Bundle）として成る。プロジェクトの現在地を知ること。',
        'pill.creationModel': '創造のモデル',
        'pill.awarenessModel': '意識のモデル',
        'section.direction.label': 'Direction',
        'section.direction.title': '今後の方向性',
        'section.direction.body': '本ページで固定した「射程・領域・Doing/Beingの二分」は基底（土台・骨格）です。以降の各ページは、この骨格の上に展開します。',
        'repo.kesson': '欠損駆動思考',
        'repo.creation': '創造とは',
        'repo.awareness': '意識とは',
        'knowledge.designThinking.title': 'デザイン思考とは',
        'knowledge.trust.title': '信頼とは',
        'knowledge.value.title': '価値とは',
        'modal.aboutTitle': 'このサイトについて',
        'modal.close': '閉じる',
        'modal.knowledgeTitle': '調査ノート',
        'knowledge.pdf.pending': 'PDF準備中',
        'knowledge.pdf.open': 'PDFで読む',
    },
    en: {
        'menu.toggle': 'Menu',
        'menu.sites': 'Sites',
        'menu.home': 'HOME',
        'menu.kesson': 'KESSON-DRIVEN',
        'menu.creation': 'CREATION',
        'menu.awareness': 'AWARENESS',
        'menu.blog': 'BLOG',
        'menu.researchNotes': 'Research Notes',
        'controls.topBarAria': 'Site controls',
        'controls.languageAria': 'Language switcher',
        'hero.notice': 'Many times, I have experienced what I want to call Love-Driven Development.<br>Here, a project is an event that includes not only "Doing" but also "Being."',
        'hero.aboutAria': 'About this site',
        'section.overview.label': 'Overview',
        'section.overview.title': 'Overview',
        'overview.p1': 'Project Design is a practice that not only envisions, designs, and executes projects, but also takes the methods of execution and management themselves as its object of inquiry, and envisions and designs them.',
        'overview.p2': 'First, we fix the scope and domain as the foundation, and organize the subsequent discussion into "Doing" and "Being."',
        'overview.p3': 'Project practice can be broadly divided into environmental adaptation (material conditions) and communication (non-material conditions). This site treats environmental adaptation as prerequisite knowledge (PMBOK, etc.), decomposes communication into information processing and emotional processing, and focuses especially on emotional processing.',
        'overview.definition.title': 'Definition',
        'overview.definition.item1': 'Envisioning, designing, and executing projects',
        'overview.definition.item2': 'Envisioning and designing execution and management methods',
        'overview.scope.title': 'Scope',
        'overview.scope.body': 'Primarily applicable to profit and non-profit enterprises. Generally applicable to any endeavor where a subject acts with purpose, such as research or life itself.',
        'overview.domain.title': 'Domain',
        'overview.domain.body': 'Communication (information processing + emotional processing) and environmental adaptation (management studies, etc.)',
        'section.doing.label': 'Doing',
        'section.doing.title': 'Doing',
        'doing.principles.title': 'Principles of Action',
        'doing.principles.item1': 'Embrace diverse values',
        'doing.principles.item2': 'Achieve balance',
        'doing.principles.item3': 'Continuously adapt to the situation',
        'doing.environment.title': 'Environmental Adaptation',
        'doing.environment.body': 'Organization of material conditions based on PMBOK 7th Edition, etc. This site treats these as prerequisite knowledge and focuses on non-material conditions.',
        'doing.communication.title': 'Communication',
        'doing.communication.body': 'Information processing and emotional processing. We focus on the emotional aspects perceived through our inner responses.',
        'pill.kesson': 'Kesson-Driven Thinking',
        'pill.beauty': 'Beauty-Driven Thinking',
        'pill.emotionalProcessing': 'Emotional Processing',
        'pill.meditation': 'Meditation',
        'section.being.label': 'Being',
        'section.being.title': 'Being',
        'section.being.body': 'Fields emerge, waves of difference arise, relations form, collisions spiral, and outcomes bundle together. To know where the project stands.',
        'pill.creationModel': 'Model of Creation',
        'pill.awarenessModel': 'Model of Awareness',
        'section.direction.label': 'Direction',
        'section.direction.title': 'Future Direction',
        'section.direction.body': 'The "scope, domain, and Doing/Being dichotomy" established on this page is the foundation (base and skeleton). Each subsequent page develops upon this skeleton.',
        'repo.kesson': 'Kesson-Driven Thinking',
        'repo.creation': 'What Is Creation',
        'repo.awareness': 'What Is Awareness',
        'knowledge.designThinking.title': 'What is Design Thinking?',
        'knowledge.trust.title': 'What is Trust?',
        'knowledge.value.title': 'What is Value?',
        'modal.aboutTitle': 'About this site',
        'modal.close': 'Close',
        'modal.knowledgeTitle': 'Research note',
        'knowledge.pdf.pending': 'PDF pending',
        'knowledge.pdf.open': 'Open PDF',
    },
};
