# T-layer machine verification for RR-010 O3 (pd#115, octonions / 7-person)
# Alternative law (Artin): the subalgebra generated by any TWO octonions is
# associative. Equivalently, the associator (x,y,z) = (xy)z - x(yz) is an
# alternating function - it vanishes whenever two of its arguments are equal.
# Reading (RR-010 O3): the breakdown of "order does not matter" starts only
# from a THIRD (distinct) element; between any two, sequencing stays free.
import math
import random

random.seed(1)


def qmul(a, b):
    a0, a1, a2, a3 = a
    b0, b1, b2, b3 = b
    return (
        a0 * b0 - a1 * b1 - a2 * b2 - a3 * b3,
        a0 * b1 + a1 * b0 + a2 * b3 - a3 * b2,
        a0 * b2 - a1 * b3 + a2 * b0 + a3 * b1,
        a0 * b3 + a1 * b2 - a2 * b1 + a3 * b0,
    )


def qconj(a):
    return (a[0], -a[1], -a[2], -a[3])


def omul(x, y):
    # Cayley-Dickson doubling of quaternions: (a,b)(c,d) = (ac - d* b, d a + b c*)
    a, b = x[:4], x[4:]
    c, d = y[:4], y[4:]
    ac = qmul(a, c)
    db = qmul(qconj(d), b)
    da = qmul(d, a)
    bc = qmul(b, qconj(c))
    left = tuple(ac[i] - db[i] for i in range(4))
    right = tuple(da[i] + bc[i] for i in range(4))
    return left + right


def sub(x, y):
    return tuple(x[i] - y[i] for i in range(8))


def norm(x):
    return math.sqrt(sum(c * c for c in x))


def assoc(x, y, z):
    return sub(omul(omul(x, y), z), omul(x, omul(y, z)))


def rnd():
    return tuple(random.gauss(0, 1) for _ in range(8))


print("=== O3: alternative law (order breaks only from a third element) ===\n")

print("(1) associators with a repeated argument vanish (alternativity)")
maxs = []
for _ in range(200):
    x, y = rnd(), rnd()
    for trip in [(x, x, y), (x, y, y), (x, y, x)]:
        maxs.append(norm(assoc(*trip)))
print(f"    max |[a,a,b]|,|[a,b,b]|,|[a,b,a]| = {max(maxs):.2e}  -> effectively 0")

print("\n(2) three DISTINCT elements give a live associator (break needs a third)")
lives = 0
sample = []
for _ in range(200):
    x, y, z = rnd(), rnd(), rnd()
    n = norm(assoc(x, y, z))
    if n > 1e-9:
        lives += 1
    if len(sample) < 3:
        sample.append(round(n, 3))
print(f"    nonzero associator with 3 distinct = {lives}/200  e.g. {sample}")

ok = max(maxs) < 1e-9 and lives > 0
print("\n=== conclusion ===")
print("The associator is alternating: with only two elements present it is 0 (associative).")
print("Sequencing (bracketing) matters only once three distinct, off-line elements appear.")
print("-> O3 math side fixed: the break starts from the third; between any two, order stays free.")
print("ALL CHECKS PASSED" if ok else "CHECK FAILED")
