# T-layer machine verification for RR-010 O3 (pd#115, octonions / 7-person)
# Alternative law (Artin): the subalgebra generated by any TWO octonions is
# associative. Equivalently, the associator (x,y,z) = (xy)z - x(yz) is an
# alternating function - it vanishes whenever two of its arguments are equal.
# Reading (RR-010 O3): the breakdown of "order does not matter" starts only
# from a THIRD (distinct) element; between any two, sequencing stays free.
import math
import random

random.seed(1)


def qmul(a, b):
    a0, a1, a2, a3 = a
    b0, b1, b2, b3 = b
    return (
        a0 * b0 - a1 * b1 - a2 * b2 - a3 * b3,
        a0 * b1 + a1 * b0 + a2 * b3 - a3 * b2,
        a0 * b2 - a1 * b3 + a2 * b0 + a3 * b1,
        a0 * b3 + a1 * b2 - a2 * b1 + a3 * b0,
    )


def qconj(a):
    return (a[0], -a[1], -a[2], -a[3])


def omul(x, y):
    # Cayley-Dickson doubling of quaternions: (a,b)(c,d) = (ac - d* b, d a + b c*)
    a, b = x[:4], x[4:]
    c, d = y[:4], y[4:]
    ac = qmul(a, c)
    db = qmul(qconj(d), b)
    da = qmul(d, a)
    bc = qmul(b, qconj(c))
    left = tuple(ac[i] - db[i] for i in range(4))
    right = tuple(da[i] + bc[i] for i in range(4))
    return left + right


def sub(x, y):
    return tuple(x[i] - y[i] for i in range(8))


def norm(x):
    return math.sqrt(sum(c * c for c in x))


def assoc(x, y, z):
    return sub(omul(omul(x, y), z), omul(x, omul(y, z)))


def rnd():
    return tuple(random.gauss(0, 1) for _ in range(8))


print("=== O3: alternative law (order breaks only from a third element) ===\n")

print("(1) associators with a repeated argument vanish (alternativity)")
maxs = []
for _ in range(200):
    x, y = rnd(), rnd()
    for trip in [(x, x, y), (x, y, y), (x, y, x)]:
        maxs.append(norm(assoc(*trip)))
print(f"    max |[a,a,b]|,|[a,b,b]|,|[a,b,a]| = {max(maxs):.2e}  -> effectively 0")

print("\n(2) generic three distinct elements give a live associator")
lives = 0
sample = []
for _ in range(200):
    x, y, z = rnd(), rnd(), rnd()
    n = norm(assoc(x, y, z))
    if n > 1e-9:
        lives += 1
    if len(sample) < 3:
        sample.append(round(n, 3))
print(f"    nonzero associator with 3 generic = {lives}/200  e.g. {sample}")

# V3 counterexample pass (2026-07-03): the precise claim is NOT "3 distinct"
# but "3 elements not all inside one 2-generated (associative) subalgebra".
# A third element that is merely a combination of the two keeps associativity.
def add(*xs):
    return tuple(sum(x[i] for x in xs) for i in range(8))


def scal(s, x):
    return tuple(s * x[i] for i in range(8))


E0 = tuple(1.0 if k == 0 else 0.0 for k in range(8))

print("\n(3) V3: a third element INSIDE <1,a,b,ab> keeps associativity")
inside_bad = 0
for _ in range(300):
    a, b = rnd(), rnd()
    ab = omul(a, b)
    z = add(scal(random.gauss(0, 1), E0), scal(random.gauss(0, 1), a),
            scal(random.gauss(0, 1), b), scal(random.gauss(0, 1), ab))
    for trip in [(a, b, z), (a, z, b), (z, a, b)]:
        if norm(assoc(*trip)) > 1e-9:
            inside_bad += 1
print(f"    nonzero associator with z in <1,a,b,ab> = {inside_bad}/900  -> must be 0")

print("\n(4) control: mixing an independent 4th direction breaks it (break is truly from outside)")
outside_break = 0
for _ in range(300):
    a, b = rnd(), rnd()
    zp = add(omul(a, b), scal(0.5, rnd()))
    if norm(assoc(a, b, zp)) > 1e-9:
        outside_break += 1
print(f"    nonzero associator with outside direction = {outside_break}/300")

ok = max(maxs) < 1e-9 and lives > 0 and inside_bad == 0 and outside_break > 0
print("\n=== conclusion ===")
print("The associator is alternating: with only two generators present it is 0 (associative).")
print("Any third element still inside the 2-generated subalgebra stays associative (3);")
print("the break appears only when a genuinely independent (off-subalgebra) third enters (4).")
print("-> O3 math side fixed: the break starts from a third OUTSIDE the two's shared subalgebra;")
print("   between any two, and for any third that is merely their combination, order stays free.")
print("ALL CHECKS PASSED" if ok else "CHECK FAILED")
